autoDetectedPackages:
- com.yun.weblog.admin.config
- com.yun.weblog.admin.controller
- com.yun.weblog.admin.model.vo
- com.yun.weblog.admin.service
- com.yun.weblog.common.aspect
- com.yun.weblog.common.config
- com.yun.weblog.common.domain.dos
- com.yun.weblog.common.domain.mapper
- com.yun.weblog.common.enums
- com.yun.weblog.common.exception
- com.yun.weblog.common.model
- com.yun.weblog.common.result
- com.yun.weblog.common.utils
- com.yun.weblog.jwt.config
- com.yun.weblog.jwt.exception
- com.yun.weblog.jwt.filter
- com.yun.weblog.jwt.handler
- com.yun.weblog.jwt.model
- com.yun.weblog.jwt.service
- com.yun.weblog.jwt.utils
- com.yun.weblog.web
enableAutoDetect: true
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
